# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'YLPhoto' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!
  pod 'GPUImage'
  pod 'SDWebImage'
  pod 'ZLPhotoBrowser'
  # Pods for YLPhoto

end
